[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "polars>=1.37.1",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
